// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDlJSFOo7a68DJwvPV01R6iQO17C_lxp0',
    appId: '1:558228969835:web:b5f16af9b46f1da3bcd42e',
    messagingSenderId: '558228969835',
    projectId: 'todolistapp-44ad8',
    authDomain: 'todolistapp-44ad8.firebaseapp.com',
    storageBucket: 'todolistapp-44ad8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvtrx6WY0l6pGAo4wGgzPtjvWyqCDoBZ8',
    appId: '1:558228969835:android:bc1293894e92bffbbcd42e',
    messagingSenderId: '558228969835',
    projectId: 'todolistapp-44ad8',
    storageBucket: 'todolistapp-44ad8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClaMNIN6dKgaFniL6d-KAByzcNco5SnQI',
    appId: '1:558228969835:ios:07122a3eaa3d493bbcd42e',
    messagingSenderId: '558228969835',
    projectId: 'todolistapp-44ad8',
    storageBucket: 'todolistapp-44ad8.appspot.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClaMNIN6dKgaFniL6d-KAByzcNco5SnQI',
    appId: '1:558228969835:ios:07122a3eaa3d493bbcd42e',
    messagingSenderId: '558228969835',
    projectId: 'todolistapp-44ad8',
    storageBucket: 'todolistapp-44ad8.appspot.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDlJSFOo7a68DJwvPV01R6iQO17C_lxp0',
    appId: '1:558228969835:web:32abdb9808d477c8bcd42e',
    messagingSenderId: '558228969835',
    projectId: 'todolistapp-44ad8',
    authDomain: 'todolistapp-44ad8.firebaseapp.com',
    storageBucket: 'todolistapp-44ad8.appspot.com',
  );
}
